### ISSUE TITLE
Get-VMProcessor : Hyper-V was unable to find a virtual machine with name

### ISSUE THREAD

**Issue by tbturbo** [taliesins/terraform-provider-hyperv#85] opened 2021-11-09 10:29 UTC
### Terraform Version
Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/taliesins/hyperv v1.0.3

### Affected Resource(s)
Please list the resources as a list, for example:
- hyperv_machine_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "random_integer" "vm_prefix" {
  max = 1000
  min = 0
}

terraform {
  required_providers {
    hyperv = {
      source  = "taliesins/hyperv"
      version = ">=1.0.3"
    }
  }
}

provider "hyperv" {
  user     = "***"
  password = "****"
  host     = "***"
  port     = 5986
  https    = true
  insecure = true
  use_ntlm = true
}

module "single_vm" {
  source = "../.."

  hyperv_host_name = "***"
  generation       = 2
  vm_name          = "${random_integer.vm_prefix.id}-uefi-test"
  num_cpus         = 1
  memory_gb        = 1
  template_disk    = "redhat-8.3-x86_64-07.uefi\\Virtual Hard Disks\\redhat-8.3-x86_64-07.uefi.vhdx"
  host_vm_dir      = "c:\\test\\testvm\\"
  controller_type  = "Scsi"

}

output "ip_address" {
  value = module.single_vm.ip_address
}

output "name" {
  value = module.single_vm.vm_name
}

```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Resource should be marked as destroyed (Same behaviour as vsphere provider)

### Actual Behavior
Error: run command operation returned code=1
│ stderr:
│ 
│ stdOut:
│ Get-VMProcessor : Hyper-V was unable to find a virtual machine with name "965-uefi-test".
│ At C:\Users\geoadmin\AppData\Local\Temp\shell-terraform-20g3b1eXS7INEVWQmpvNaZuy1Op.ps1:4 char:22
│ + $vmProcessorObject = Get-VMProcessor -VMName '965-uefi-test' | %{ @{
│ +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
│     + CategoryInfo          : ObjectNotFound: (:) [Get-VMProcessor], VirtualizationException
│     + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVMProcessor
│ 
│   with module.single_vm.hyperv_machine_instance.default,
│   on ../../main.tf line 31, in resource "hyperv_machine_instance" "default":
│   31: resource "hyperv_machine_instance" "default" {

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a VM with terraform
2. Remove it manually
3. Run terraform destroy (or plan)

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by rismoney** [comment] 2022-02-14 23:00
I can confirm I am experiencing the same behavior around idempotency.  Just looking at the code here,
https://github.com/taliesins/terraform-provider-hyperv/blob/master/api/vm_processor.go#L198-L215

It looks like it should probably use a try/catch here (or similar logic) for the case where get-vmprocessor errors because it can't find the VM with the matching name.  Might be cleaner than -ea silentlycontinue, since albeit since the end result would be an {} either way, intent would be clearer.

**Comment by taliesins** [comment] 2022-04-17 19:30
@tbturbo could you provide the contents of the module. I am not sure how to reproduce this.

**Comment by taliesins** [comment] 2022-12-15 00:52
Closing as thread has gone cold

**Closed by taliesins** 2022-12-15 00:52 UTC
Labels: needs additional info
